# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: Apache-2.0

name: nomad

on:
  - push

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Nomad
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `nomad`
        uses: nferch/setup-nomad@main
        id: setup
        with:
          version: "1.5.3" # or latest

      - name: Run `nomad validate`
        id: validate
        run: "nomad validate ./job.nomad"
